version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run syntax checks
          command: npm test
workflows:
  test-workflow:
    jobs:
      - test
